[package]
name = "justcash_core"
version = "0.1.0"
edition = "2024"
description = "core types for justcash crate"
license = "AGPL-3.0-only"

[dependencies]
risc0-zkvm = { version = "^3.0.3", default-features = false, features = ['std'] }
serde = "1.0.228"
