[package]
name = "justcash"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^3.0.3", default-features = false, features = ['std', 'disable-dev-mode'] }
justcash_core = { path = "../core", version = "0.1.0"  }
